### ISSUE TITLE
Further clarify Ledger post that tokens are not ON the device

### ISSUE THREAD

**Issue by Swader** [bitfalls/bitfalls_content#5]
There's a misconception STILL floating around that tokens are stored ON a ledger.

Explain why:

- this is not the case
- the ledger has very little disk space (anti-malware measure)
- deleting and reinstalling wallet programs doesn't ruin tokens

**Comment by wubwub** [comment]
On it!

**Comment by maaxaam** [comment]
Dunno if you still need this...

Digital Tokens
Cryptocurrency tokens don’t exist as a string like we saw above (if they did, they would be easy to copy). Rather, they exist conceptually as entries on a ledger (a blockchain). You own these ‘tokens’ because you have a key that lets you create a new entry on the ledger, re-assigning the ownership to someone else. You don’t store tokens on your computer, you store the keys that let you reassign the quantity.

Think of these ‘tokens’ as specific amounts of digital resources that you control and you can reassign control to someone else.

We’ll cover two types of tokens:

“intrinsic” or “native” or “built-in” tokens of blockchains
“asset-backed” tokens issued by a party onto a blockchain for later redemption
1. Intrinsic tokens (also known as ‘native or ‘built-in’ tokens)

Intrinsic tokens are made-up resources that have some utility.
Some of the more well known examples of intrinsic tokens are:

BTC on the Bitcoin blockchain
XRP on the Ripple network
NXT on the NXT platform
ETH on Ethereum

These ‘coins’ or ‘tokens’ form part of the core of the blockchain, and the blockchain would not run without them. They are usually part of an incentive scheme to encourage people to validate transactions and create blocks (miners), or in Ripple’s case, they are there to create a small cost per transaction which helps prevent transaction spam.

2. Asset-backed tokens

Asset backed tokens are claims on an underlying asset, from a specific issuer.

Wikipedia’s History of money suggests that in the good ole' days, you could park some gold with a goldsmith, and receive a receipt or “I Owe You” (IOU) note from them. These notes could be transferred from person to person, and anyone holding these notes could go back to the goldsmith and claim the actual gold.

Asset-backed tokens are the digital equivalent. They are claims on an underlying asset (like gold), that you need to claim from a specific issuer (the goldsmith). The transactions, which are tokens passed between people, are recorded on the blockchain, and to claim the underlying asset, you send your token to the issuer and the issuer sends you the underlying asset.

Popular assets for these schemes are currency (USD, EUR, etc) and precious metals (Cryptocurrencies seem to attract the same crowd as gold and silver). However, read the news and everyday you’ll see people tracking assets on ledgers by creating a digital token that represents them. Diamonds, art, music… you name it.
